const FIRST_NUMBER = "FIRST_NUMBER"
const SECOND_NUMBER = "SECOND_NUMBER"
const OPERATOR = "OPERATOR"
const SUM_ANSWER = "SUM_ANSWER"
const SUBTRACT_ANSWER = "SUBTRACT_ANSWER"
const USER_ANSWER = "USER_ANSWER"
const CLEAR_USER_ANSWER = "CLEAR_USER_ANSWER"
const CLEAR_PROBLEM = "CLEAR_PROBLEM"

const INCREASE_SCORE = "INCREASE_SCORE"
const REDUCE_SCORE = "REDUCE_SCORE"

const SUCCESS_PHRASE = "SUCCESS_PHRASE"

export {
    FIRST_NUMBER,
    SECOND_NUMBER,
    OPERATOR,
    SUM_ANSWER,
    SUBTRACT_ANSWER,
    USER_ANSWER,
    CLEAR_USER_ANSWER,
    CLEAR_PROBLEM,

    INCREASE_SCORE,
    REDUCE_SCORE,

    SUCCESS_PHRASE
}